
# frozen_string_literal: true
source "https://gems.ruby-china.org/"

gem "sinatra"
gem "debase"
gem "mysql2"
gem "haml"
gem "rufus-scheduler"
gem "logger"
gem "eventmachine"
gem "redis"
gem "fastimage"
gem "bcrypt"
gem "qiniu"
gem "passenger"
gem "rmagick"
gem "mechanize"
gem "iconv"
gem "ruby-pinyin"
gem "thin"
gem "ffi"
gem "rchardet"
gem "multipart-post"
